cmd/main.go, pkg/common/constants.go
fix: Enforce sane concurrency limit
feat: Introduce dry run mode
fix: Correctly get Helm target params
fix: Typo in annotation names for Helm target parameters
=> Multiple fixes and dry run mode

CHANGELOG.md, cmd/main.go, go.mod, go.sum, pkg/cache/cache.go, pkg/cache/memcache.go, pkg/cache/memcache_test.go, pkg/image/version.go, pkg/image/version_test.go, pkg/registry/endpoints.go, pkg/registry/registry.go, pkg/tag/tag.go
This PR introduces fetching some metadata along with the tag from the registry, and also a simple in-memory cache for storing this (immutable) metadata
=> enhancement: Store tag metadata and introduce metadata cache

CHANGELOG.md, cmd/main.go, pkg/common/constants.go, pkg/image/options.go, pkg/image/options_test.go, pkg/image/version.go
This will allow setting the tag sorting mechanism - and thereby ultimately which tag to update to - by setting an annotation:
`argocd-image-updater.argoproj.io/<image>.sort: <sortmode>`
where `<sortmode>` can be one of:
* `semver` (the default) - sort by latest version
* `date` - sort by creation date, i.e. take the latest built image
* `name` - sort by tag name
This will be useful if you want to upgrade to the latest image (i.e. those who have a Git hash in the tag) or if you have another version scheme than semver.
=> feat: Allow setting tag sorting per image via annotation

cmd/main.go
As result of #59, the default value for `--registries-conf-path` is now `/app/config/registries.conf`.
=> fix: Use a default path for registries.conf

.github/actions/spelling/allow.txt, docs/configuration/registries.md, pkg/registry/config.go, pkg/registry/endpoints.go, pkg/registry/endpoints_test.go, pkg/registry/registry.go
Allows configuration of a default image namespace to use when the image name doesn't specify one (i.e. DockerHub has a default namespace of `library`).
Might help resolution of #90
=> feat: Allow configuration of default namespace for registries

.github/actions/spelling/allow.txt, docs/configuration/registries.md, pkg/registry/config_test.go, pkg/registry/endpoints.go
Adds out-of-the-box support for the new ghcr.io registry from GitHub. 
Closes #95
=> feat: Support for GitHub Container Registry (ghcr.io)

docs/configuration/images.md, pkg/argocd/update_test.go, pkg/common/constants.go, pkg/image/options.go, pkg/image/options_test.go
The `tag-match` annotation has been deprecated and renamed in favour of `allow-tags` to be more consistent with the new `ignore-tags` annotation.
The `tag-match` annotation will still work for a couple of versions before being removed, but a warning is printed in the logs.
=> refactor: Introduce allow-tags and deprecate tag-match annotation

pkg/registry/registry.go
The tag ignore list was not applied when match function wasn't specified also.
This change correctly applies the ignore list, even when the match function is not set.
=> fix: Correctly apply ignore list when matchfunc is not set

cmd/main.go
This adds the new `test` command to `argocd-image-updater` CLI.
Its main purpose is to test & validate behaviour of argocd-image-updater, without requiring changes to your live resources.
=> feat: add argocd-image-updater test command

.github/actions/spelling/allow.txt, go.mod, go.sum, pkg/argocd/update_test.go, pkg/registry/client.go, pkg/registry/config.go, pkg/registry/endpoints.go, pkg/registry/endpoints_test.go, pkg/registry/mocks/RegistryClient.go, pkg/registry/registry.go, pkg/registry/registry_test.go
This change implements two new features:
* pulling tag meta-data in parallel for better performance of `latest` mode and
* basic rate-limiting of requests to the registry (configurable per endpoint/registry)
=> feat: Implement rate limiter and metadata parallelism

pkg/registry/endpoints.go
This change sets the default rate limiter for all pre-configured registries to 10 requests per second max.
=> fix: Provide sane rate limiter defaults

.github/actions/spelling/allow.txt, go.mod, go.sum, pkg/argocd/update_test.go, pkg/registry/client.go, pkg/registry/mocks/RegistryClient.go, pkg/registry/registry.go, pkg/registry/registry_test.go
This change moves the rate limiter downstream into a custom `http.RoundTrip` object, so it will handle all outgoing HTTP requests.
=> refactor: Better integration of rate limiter

.github/actions/spelling/allow.txt, cmd/main.go, go.mod, pkg/image/credentials.go, pkg/image/credentials_test.go, test/testdata/scripts/get-credentials-invalid.sh, test/testdata/scripts/get-credentials-valid.sh
This PR adds support for a new type of credential source for image pull secrets: `ext`
This credential source can specify a script to execute, and will use the output of the script to define the credentials. Output of the script must be a single line in the format `username:password`.
This will allow users to authenticate with third parties that require volatile tokens for authentication.
=> feat: Support for getting pull creds from external scripts

.github/actions/spelling/allow.txt, .github/actions/spelling/excludes.txt, cmd/main.go, config/example-grafana-dashboard.json, docs/install/start.md, go.mod, go.sum, pkg/argocd/argocd.go, pkg/argocd/update.go, pkg/client/kubernetes.go, pkg/metrics/metrics.go, pkg/registry/client.go
This PR adds first set of Prometheus-compatible metrics to argocd-image-updater.
Fixes #122 
=> feat: Export Prometheus compatible metrics

.github/actions/spelling/expect.txt, cmd/main.go, docs/configuration/applications.md, manifests/base/rbac/argocd-image-updater-role.yaml, manifests/install.yaml, pkg/argocd/gitcreds.go, pkg/argocd/update.go, pkg/argocd/update_test.go, pkg/common/constants.go, pkg/kube/kubernetes.go, pkg/kube/kubernetes_test.go, test/fixture/kubernetes.go
Closes https://github.com/argoproj-labs/argocd-image-updater/issues/138
PR implements proposal described in https://github.com/argoproj-labs/argocd-image-updater/issues/138 . The default credentials source is "repocreds" since it requires no configuration.
=> feat: Allow reuse of Argo CD repo credentials

cmd/main.go, docs/install/start.md, manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/base/rbac/argocd-image-updater-role.yaml, manifests/install.yaml, pkg/argocd/argocd.go, pkg/argocd/argocd_test.go, pkg/kube/kubernetes.go
Closes https://github.com/argoproj-labs/argocd-image-updater/issues/140 
PR implements proposal from  https://github.com/argoproj-labs/argocd-image-updater/issues/140:
* By default image updater tries to manage Argo CD applications in the same namespace where it is running using K8S API 
* Namespace can be changed using `--argocd-namespace` flag
* Updater can be switch back to Argo CD API using `--applications-api argocd` flag (or `APPLICATIONS_API` env variable).
=> feat: support managing Application CRD using K8S client (#140)

docs/install/start.md, manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/install.yaml
https://github.com/argoproj-labs/argocd-image-updater/issues/109
PR make `argocd-image-updater-config` ConfigMap volume optional to simplify bootstapping process. The image updater fallback to "default" registries configuration and still support public image registries.
=> refactor: make argocd-image-updater-config volume mapping optional

Dockerfile, hack/git-ask-pass.sh
PR adds missing `git-ask-pass.sh` that is required for password based authentication
=> fix: add missing git-ask-pass.sh to support password auth

pkg/health/health.go, pkg/metrics/metrics.go
=> fix: Use dedicated HTTP muxers for health and metrics endpoints

Dockerfile
This adds the openssh-client to the container image, which will be used for connecting to Git repositories via SSH.
Closes #163
=> chore: Add openssh-client to container image

pkg/argocd/update.go
This will hopefully fix #170.
Prevent an update loop with Git write-back when not all of the images needed update by including also the non-updated images in the list of images to update.
=> fix: Prevent update loop with git write-back

cmd/main.go, manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/base/kustomization.yaml, manifests/base/rbac/argocd-image-updater-role.yaml, manifests/install.yaml, pkg/argocd/update.go, pkg/kube/kubernetes.go, pkg/kube/kubernetes_test.go
Sends an event on any image change (fixes #164)
I thought in re-using some argo-cd code, but finally I decided to copy and adapt it. It is the code related to send the event.
The namespace used is the one where argocd-image-updater is running in order to reduce the permissions required (a Role instead a ClusterRole).
I had to add some argo-cd dependencies to the kubernetes package, what is... ugly. Maybe you know a better way to do it.
Finally, understand this is my first golang contribution... I'm open to changes XD
NOTE: I didn't tested it under real fire. I have no docker repository accessible from my laptop.
=> #164 Send events on image change

pkg/tag/tag.go, pkg/tag/tag_test.go
Fixes #147 
If two images have the same date, return the same consistently. It doesn't matter which one to choose, but it always must be the same, so I decided to sort them by name.
=> Multiple tags on the same image return same order

pkg/argocd/update.go, pkg/argocd/update_test.go, pkg/image/version.go
This fixes a nil pointer dereference when there's an image without tag specification in the application's status.
=> fix: Prevent nil pointer deref on emtpy tag with running image

docs/configuration/images.md, pkg/argocd/argocd.go, pkg/argocd/argocd_test.go, pkg/common/constants.go, pkg/image/image.go
Supports #187. I've tested against my deployment of a PodTemplate it works wonderfully :)
=> allow image updates to be forced if container not present #181

pkg/argocd/argocd.go, pkg/argocd/argocd_test.go, pkg/argocd/update.go, pkg/argocd/update_test.go, pkg/image/image.go, pkg/image/options.go
Given this config:
```
imageList: foo=gcr.io/bar:>=1.0.0
foo.kustomize.image-name=bar
```
If my application is running `bar:1.0.0` I'd expect an update to `gcr.io/bar:1.0.0`, however that was not happening because only tag was considered in the difference. To fix that, I had to add an extra "KustomizeImage" to also be considered for matching purposes, and add registry and name to the update check if this kustomize image is present.
I've added an additional test to show that once updated there should be no more updates (no endless loop of updates, etc.)
This is builds off of #192
=> fix : Images not updated if registry or repository is different with same version

pkg/argocd/update.go
Marshal non-updated images with correct parametrisation.
Fixes #202 
=> fix: Correctly marshal non-updated images

manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/install.yaml
The default behavior of image updater is to use argocd credentials. If it is setup with ssh, this volume mounts and volume are needed in order for image updater to be able to commit to the repository
=> feat(manifests): add ssh volume mounts and volume

ext/git/client.go
fix if use `Branch()`, it will type `git` command twice
- current
```sh
git git checkout sourceBranch
git git branch targetBranch
```
- fixed
```sh
git checkout sourceBranch
git branch targetBranch
```
=> fix(ext/git): Branch method not call runCmd correctly

pkg/registry/registry.go
This fixes a possible race condition when fetching tag metadata from a registry.
_Should_ fix #214, however I am not able to reproduce the original issue.
=> fix: Fix a possible race condition in metadata retrieval

pkg/image/version.go, pkg/image/version_test.go
Do not return the original tag if no tag found in a repository was considered for being upgradeable to.
This fixes a scenario with `digest` update strategy, where a tag to track was specified as constraint but did not exist in the registry. This led to an update of the image to the (non-existing) tag, instead of just ignoring it.
Fixes #217
=> fix: Don't set tag used as constraint for update if no tag was considered from registry

docs/configuration/images.md
The available annotations table shows `<image_alias>.kustomize.image-name`, but the examples use `<image_alias>.kustomize.image_name`.
`<image_alias>.kustomize.image-name` would be the correct annotation.
=> Update docs: kustomize.image_name -> kustomize.image-name

pkg/argocd/argocd.go, pkg/argocd/argocd_test.go
In the previous implementation, there was a problem that argocd-image-updater would create a new image when using newName of kustomize.
This is due to the fact that the current kustomize image information retrieved from the argucd API does not include the value of alias_name.
(`[<alias_name>=]<image_path>[:<version_constraint>]`)
So, in this PR, even if the current image information doesn't contain alias_name, we can update the kustomize image information appropriately
application.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: adservice
annotations:
argocd-image-updater.argoproj.io/image-list: adservice=nyuta01/adservice:^1.0.0
argocd-image-updater.argoproj.io/write-back-target: kustomization
argocd-image-updater.argoproj.io/adservice.kustomize.image-name: …
```
=> fix: modify SetKustomizeImage logic when use alias_name

pkg/argocd/update.go, pkg/argocd/update_test.go
=> fix: Get tags from correct registry/image with a different kustomize image

docs/install/start.md
The metrics server is running on port 8081 and not 8082 as mentioned in the docs. This PR fixes that.
=> docs: Fix metrics port in docs

pkg/argocd/update.go, pkg/argocd/update_test.go
ADD a test case for Update Two Images, FIX `result.NumImagesUpdated`
=> chore: Test successful update two images

pkg/argocd/update_test.go
Fixes unit test from #264 after #266 had been merged.
=> chore: Fix unit test

cmd/test.go
This PR fixes the issue described in #288.
For the following cases, I used the following `registries.conf`:
```yaml
registries:
- name: myfancyregistry
api_url: https://myfancyregistry.azurecr.io
prefix: myfancyregistry.azurecr.io
ping: yes
credentials: secret:argocd/registry#auth
```
```
$ argocd-image-updater --registries-conf registries.conf test myfancyregistry.azurecr.io/example
DEBU[0000] Creating in-cluster Kubernetes client        
INFO[0000] getting image                                 image_name=example registry=myfancyregistry.azurecr.io
DEBU[0000] rate limit for https://myfancyregistry.azurecr.io is 2147483647 
INFO[0000] Loaded 1 registry configurations from registries.yaml 
INFO[0000] Fetching available tags and metadata from registry  image_name=example
INFO[0001] Found 2 …
```
=> Allow use of in-cluster kube-client for test-command

cmd/test.go
This PR renames `--registries-conf` of the `test`-command to `--registries-conf-path` like we already use for the `run`-command.
The issue has been described in #290.
=> Have consistent flag to specify registries conf path

docs/install/start.md
The non-quoted true, false variable assignment in the `argocd-image-updater-config` ConfigMap is causing failures. Quoted them now.
=> docs: Update quoted true, false in configmap

pkg/argocd/argocd.go, pkg/image/image.go, pkg/image/image_test.go
Fixes #259 #210
When using digest update strategy, the helm image.tag parameter now composes a full tag of both the tag and the digest in the form:
```
sometag@sha256:<somelonghashstring>
```
This avoids invalid references in almost all helm charts that construct the image ref as `image.repository:image.tag`, that so far resulted to the invalid references of the form:
```
some/image:sha256:<somelonghashstring>
```
=> fix: Invalid image reference format when using digest strategy with helm charts

pkg/argocd/argocd.go, pkg/argocd/argocd_test.go
Recently started using tooling based on kustomize that is configured in Argo as a plugin. It stopped getting updates, so this is a workaround to continue to get kustomize updates.
=> feat: Assume app type when write-back-type is set to kustomize

go.sum, pkg/kube/kubernetes.go
This PR enables the default auth plugins in order to obtain credentials from cloud providers when required.
=> feat: Enable auth plugins for Kubernetes client

docs/configuration/registries.md
The code block used `gcr` for GitHub Container Registry, changed them to `ghcr`
=> docs: Fixed typo

docs/configuration/registries.md
The docs mentioned `argocd-image-updater-cm` while the correct name is `argocd-image-updater-config`
=> docs: Fixed ConfigMap name

pkg/registry/client.go, pkg/registry/endpoints.go
Related to #329
Previously, when a registry's API URL was specified with a trailing slash, authentication would fail due to an invalid request being sent to the registry for the `/v2` endpoint. This change removes any trailing slash from the URL before using it. Also, handle authentication errors early on.
=> fix: Fix registry authentication when URL has slash suffix

pkg/registry/client.go
`schema1.SchemaVersion.MediaType` expands to the empty string, because it is not correctly initialized. This changes it to use a specific mediatype for the request.
Fixes #306 
=> fix: Request correct mediatype for v1 manifests

hack/release.sh
Allow multiple-digit versions in the release script.
=> chore: Small fix to the release script

docs/configuration/applications.md, pkg/argocd/git.go, pkg/argocd/git_test.go, pkg/argocd/update.go, pkg/argocd/update_test.go, pkg/common/constants.go
This add new functionality by adding a write-branch to `argocd-image-updater.argoproj.io/git-branch` using a separator, which will be used to push back changes to the target repository. The branch from the Application's spec or specified with the existing `git-branch` annotation will be used as the base branch for checkout.
Further, this annotation can use Golang templating to allow for dynamic branch names based off of the changes.
This could integrate with various CI/CD (such as GitHub Actions) to automatically create a pull request.
This varies slightly from the suggestion in #198, though sill resolves the issue. Rather than adding a new annotation to specify the base branch, we're specifying a write branch. This decision was made for ease of implementation, as rather than having to …
=> feat: add ability to specify a different write and base branch

pkg/registry/registry.go
When using digest update strategy, the Image Updater would have fetched metadata for all tags returned by the registry. For digest strategy, caching is also disabled and this leads to too many requests to the registry.
Now, only metadata for the tag specified in the version constraint is fetched. All other tags are skipped.
Fixes #313
=> fix: Do not retrieve metadata for all tags with digest strategy

pkg/registry/endpoints.go
use HTTP_PROXY in transport object for registry endpoint if defined in environment
=> feat: use HTTP_PROXY for registry endpoint

cmd/test.go, pkg/argocd/update.go, pkg/image/version.go, pkg/options/options.go, pkg/options/options_test.go, pkg/registry/client.go
Small bugfix for `latest` update strategy and multi-arch images
=> fix: Fetch metadata for multi-arch images with latest strategy

cmd/test.go, pkg/argocd/update.go, pkg/image/options.go, pkg/image/options_test.go, pkg/image/version.go, pkg/image/version_test.go, pkg/registry/registry.go, pkg/registry/registry_test.go
=> refactor: rename VersionSortMode to UpdateStrategy

pkg/argocd/argocd.go
This PR improves visibility on why a given app is skipped:
1) Move checks for app type and name matching after we found out that its correctly annotated
2) Issue a warning message instead of a trace message if the application has not the correct type
3) If an application doesn't match a name pattern, issue a debug message instead of a trace message
=> feat: Improve visibility for skipped apps

pkg/registry/client.go
Use the registry endpoint's transport settings when fetching token for authentication.
=> fix: Use endpoint's transport also for token handler

docs/configuration/applications.md
https://github.com/argoproj-labs/argocd-image-updater/issues/354
=> docs: Fix inconsistency in the documentation on git write-back credentials

config/example-grafana-dashboard.json, docs/install/start.md
This PR fixes the issue raised at https://github.com/argoproj-labs/argocd-image-updater/issues/314
The documentation and the grafana dashboard example are pointing to a not implemented metric instead point to the correct one `argocd_image_updater_registry_requests_failed_total`
=> fix: Use existing registry requests failed metric

pkg/argocd/update.go, pkg/image/version.go, pkg/registry/config.go, pkg/registry/endpoints.go, pkg/registry/endpoints_test.go, pkg/registry/registry.go
We have bad examples in the docs regarding `tagsortmode` registry setting.
This change logs a warning if user has specified `tagsortmode` in the configuration.
Also, some refactoring included.
=> chore: Log out warning about tagsortmode

manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/install.yaml
Set `strategy: Recreate` to stop rolling deployments with concurrent replicas
- Fixes #359
---
Looks like the workflow uses Kustomize 2.0.2. Newer versions replace `bases` with `resources` (see  b432ebe), which seems to [cause the `make manifests` check to fail](https://github.com/argoproj-labs/argocd-image-updater/runs/4909466408?check_suite_focus=true).
I used the following which failed, so I reverted the change it made.
```
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}
```
=> fix(manifests): Set deployment strategy to recreate to prevent concurrent replicas

pkg/version/version.go
Using the static string as done in `argocd`:
https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/common/version.go#L12
Fixes #366
=> fix: Hardcode buildDate so it can be updated by ld at build time

cmd/main.go, cmd/run.go, docs/install/running.md, pkg/argocd/argocd.go, pkg/argocd/argocd_test.go
This PR addresses issue #258 
It adds a new CLI parameter `--match-application-label` which accepts a string label input to match applications against
It currently only accepts a single label to filter against, and does not support pattern matching on label values, but those enhancements can be made in future PRs 
steps to test out PR:
- create annotated apps containing 1 or more labels 
- set up argocd-image-updater account & token as per documented steps
- run argocd-image-updater binary with additional  parameter `--match-application-label` and supply desired label
application should be updated with new image after sync
=> feat: support filtering apps by label in CLI

Makefile, pkg/argocd/update_test.go, pkg/registry/config.go, pkg/registry/config_test.go, pkg/registry/endpoints.go, pkg/registry/endpoints_test.go, test/testdata/registry/config/two-defaults.yaml
This new feature allows the registry API to be inferred from an image's prefix. E.g. if the image name is `my.custom.registry/some/image`, Argo CD Image Updater now won't require a dedicated configuration for the registry `my.custom.registry`, but instead assume the Docker registry API's endpoint at `https://my.custom.registry/v2`.
This works as long as the API is available via HTTPS on the same host as the registry's prefix and as long as you won't need any custom configuration for your registry, such as modified TLS settings.
=> feat: Automatic inferring of registry from image prefix

docs/configuration/images.md, pkg/argocd/update_test.go, pkg/common/constants.go, pkg/image/options.go, pkg/image/options_test.go
Currently, you're forced to specify e.g the update strategy per image, although it might be the same for all:
```yaml
metadata:
annotations:
argocd-image-updater.argoproj.io/image-list: frontend=my-fancy-frontend, backend=my-fancy-backend
argocd-image-updater.argoproj.io/frontend.update-strategy: name
argocd-image-updater.argoproj.io/backend.update-strategy: name
```
This PR adds four new annotations to allow you to specify update-strategy related options for all images in a ArgoCD application.
* `argocd-image-updater.argoproj.io/allow-tags`
* `argocd-image-updater.argoproj.io/ignore-tags`
* `argocd-image-updater.argoproj.io/force-update`
* `argocd-image-updater.argoproj.io/update-strategy`
* `argocd-image-updater.argoproj.io/pull-secret`
<sub>(**Note:** I am using the update-strategy …
=> feat: Support app-wide update-strategy annotations

pkg/argocd/git.go, pkg/argocd/update_test.go
I'm a big fan of the new feature below. It will allow us more flexible GitOps operations.
https://github.com/argoproj-labs/argocd-image-updater/pull/304
However, I found a bug after trying the feature by myself on my local environment.
It seems after creating a new branch, `Argo CD` doesn't checkout the newly created branch. In the end, the new branch is pushed without any changes committed.
So, I've moved checkout process to after branch creation.
=> Checkout after creating a new branch

pkg/argocd/git.go, pkg/argocd/update.go, pkg/common/constants.go
Hey, this change is pretty small, but I'm trying to somehow reorganize the code around the WriteBack functionality.
=> refactor(WriteBack): Target field in the WriteBackConfig

docs/configuration/images.md, docs/index.md
Add `digest` update strategy to overview
=> docs: Add digest update strategy

config/example-config-ssh-config.yaml, manifests/base/config/argocd-image-updater-ssh-config.yaml, manifests/base/config/kustomization.yaml, manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/install.yaml
Since ssh-rsa has been deprecated since OpenSSH 8.2 but some git server are still using it like Azure DevOps, its necessary to bring back this feature.
Besisdes, since for internal networks, some people use not have too much concern about deprecated algorithms, this PR can give then hability to change the ssh client and make it compatible with their systems.
configMap example:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: argocd-image-updater-ssh-config
namespace: argocd
data:
config: |
Host *
PubkeyAcceptedAlgorithms +ssh-rsa
HostkeyAlgorithms +ssh-rsa
```
This will be loaded in /app/.ssh/config as default user home path in image.
=> feat: Add configMap to allow define parameters for SSH client

docs/basics/update-strategies.md, docs/index.md, pkg/image/options.go, pkg/image/options_test.go, pkg/image/version.go, pkg/image/version_test.go, pkg/registry/registry.go, pkg/registry/registry_test.go, pkg/tag/tag.go, pkg/tag/tag_test.go
This PR fixes https://github.com/argoproj-labs/argocd-image-updater/issues/179.
It renames `latest` strategy to `newest-build` and `name` strategy to `alphabetical`. If either of the old names is detected, it prints a warning message in the controller logs informing the user that the strategies have been renamed, and that support for them will be removed in future releases. Currently the old names are still honored. 
It also updates the documentation references for these update strategies. 
*Steps to test*:
1. Run Argo CD locally
2. Create application with some image 
3. Generate argo-cd token 
4. annotate application with either `newest-build` or `alphabetical` depending on your use case/availability of test images 
5. Run image-updater
6. app should be out of sync, and updated image …
=> feat: Rename confusing update strategies

docs/basics/authentication.md
Small fix, the flag `--docker-registry` is not a valid flag but `--docker-server` is.
Referring to the official Kubernetes documentation here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line
=> fix: Doc error --docker-server

.github/workflows/ci-tests.yaml
CI is failing on open PRs due to an older version of `golangci-lint` being used
According to https://github.com/golangci/golangci-lint/issues/2374 older versions of golangci-lint are not compatible with go v1.18
Error message is: 
```
Running [/home/runner/golangci-lint-1.32.2-linux-amd64/golangci-lint run --out-format=github-actions --timeout 5m] in [] ...
level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package goarch: could not load export data: cannot import \"internal/goarch\" (unknown iexport format version 2), export data is newer version - update tool"
level=warning msg="[runner] Can't run linter unused: buildir: failed to load package goarch: could not load export data: cannot import \"internal/goarch\" (unknown iexport format version …
```
=> chore: update golangci-lint version in CI

docs/basics/update-strategies.md
Signed-off-by: Kostis Kapelonis <kostis@codefresh.io>
When changing from latest to semver strategy, users must be careful and make sure that the existing
tag is already following semver
Otherwise trying to change from tag "rc1" to "1.0" or something similar doesn't work
=> docs: Added warning about existing tag in semver

docs/basics/update.md
Fix links that target non existing destination.
=> docs: Fix dead links

docs/basics/authentication.md
=> docs: Add missing word

go.mod, pkg/registry/client.go
=> fix: Also request OCI media type image index

README.md
Provide visibility to the proposal to integrate (graduate?) the project in the `argoproj` org and out of the lab.
=> docs(readme): add link for proposal to integrate with argo-cd

.github/workflows/ci-tests.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/image.yaml, .golangci.yml, Dockerfile, ext/git/client.go, go.mod
This PR bumps the golang release to 1.20 as requested by @jannfis in PR https://github.com/argoproj-labs/argocd-image-updater/pull/548
=> bump go version to 1.20

pkg/tag/semver.go, pkg/tag/tag.go, pkg/tag/tag_test.go
Fixes #375
The heart of the issue is that https://github.com/masterminds/semver does not yield deterministic results when sorting versions. That package (rightfully) considers `1.24` and `1.24.0`, for example, to be equal. This is fine in nearly all circumstances, but when sorting a list of versions containing both of these, these two can appear in either order, making the results of the sort non-deterministic. If one's goal were to select the latest `1.24.x`, you'd sometimes end up with `list[len(list) - 1]` being `1.24` and other times being `1.24.0`.
This PR furnishes a drop-in replacement for the `semver.Collection` type that breaks comparison ties with a lexical comparison of the origin strings from which both `Version` objects were created.
fwiw, I do plan to offer this improvement …
=> ensure deterministic results for SortBySemVer()

docs/configuration/registries.md
Docs lacks an example of the credentials environment variable, making it unclear whether it should contain dockerconfig, a login:password pair, or something else. 
This Pull Request aims to address this issue by providing the necessary example.
=> docs(registries): add env example

docs/basics/update-strategies.md
Name strategy among Update strategies, have its example have a wrong regexp. Need correction to match format mentioned in last line `YYYY-MM-DD`.  Current one is this format YYYY-MMDD (which is not what, doc wish to show)
=> Name strategy regexp in example need to be correctd 

pkg/argocd/git.go
Fixes at least one of the causes of the image kustomize write back with git failing as documented in this issue: https://github.com/argoproj-labs/argocd-image-updater/issues/240
Our Argo CD Image Updater deployment started having the same issue after switching to use Kustomize from Helm. After troubleshooting the issue with our setup, the process chdir that is happening in the write kustomization func didn't always chdir back to the original dir. Then subsequent `os.Getwd()` calls would fail with `getwd: no such file or directory` because the process working directory was still set to a previous temp dir that no longer exists. After reviewing the implementation details and testing, the chdir code doesn't appear to be needed anyway so it has been removed in the PR fixing the issue.
Note: …
=> Fix: kustomize write target starts failing after indeterminate period at time

Dockerfile, manifests/base/deployment/argocd-image-updater-deployment.yaml
As mentioned in https://github.com/argoproj-labs/argocd-image-updater/pull/583, during troubleshooting and testing for that issue, I noticed that zombie git processes were building up in the running container after each periodic image updater run. The Argo CD project had a similar issue: https://github.com/argoproj/argo-cd/issues/3611 and my fix uses the same solution
=> Fix: git zombie processes left behind after periodic image updater runs

docs/configuration/images.md
I have noticed an error in [the documentation](https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#update-strategies) related to annotations. The documentation suggests using <image_name> instead of the correct placeholder <image_alias> when working with annotations ( Update strategies, Filtering tags, Ignoring certain tags, Image platforms & Specifying pull secrets ) . This mistake can potentially misguide users and cause confusion.
=> Documentation Error: Incorrect Usage of <image_name> in Annotations

.github/workflows/ci-tests.yaml, hack/generate-manifests.sh, manifests/base/kustomization.yaml, manifests/install.yaml
Fixes codegen and upgrades  Kustomize used in the process to 5.1.0 (post-2.0)
=> ci: Fix codegen and update kustomize to post-2.0

go.mod, go.sum, pkg/argocd/git.go, pkg/argocd/update.go, pkg/argocd/update_test.go
Modification:
Make image-updater respect the original parameter overrides written in `.argocd-source-<appName>.yaml`.
Motivation:
Currently, the original overridden parameters stored in `.argocd-source-<appName>.yaml`
are not respected when image-updater writes back its change to git.
Imagine that a user has originally defined `.argocd-source-<appName>.yaml` like below
```yaml
helm:
parameters:
- name: some.prop
value: some-value
forcestring: true
```
...and image-updater wants to write back the additional overrides below
- `foo.image.repository: foo`
- `foo.image.tag: 2.0.0`
The user may want the edited file to be like...
```yaml
helm:
parameters:
- name: some.prop
value: some-value
focestring: true
- name: foo.image.repository
value: foo
forcestring: true
- name: foo.image.tag
value: …
```
=> feat: Respect original parameter overrides with git write-back

manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/install.yaml
makes argocd-image-updater compatible with restricted Pod Security Standard
=> fix: tighten securityContext to comply with restricted PSS

pkg/argocd/update_test.go, pkg/registry/client.go
I botched the commit history in #617 (rebasing is hard :rage1:) and so started a fresh branch/PR. @jannfis I hope this addresses your feedback about code duplication - I refactored most of the common code into a helper function.
=> fix: Add support for ocischema.DeserializedImageIndex manifest type

go.mod, go.sum, pkg/argocd/update_test.go, pkg/image/version.go, pkg/tag/semver.go, pkg/tag/tag.go
I attempted to use the `semver` update strategy with the `x-0` constraint.
- `x-0` signifies any tags that adhere to semantic versioning,  whether or not they have prerelease tags.
However, the constraint wasn't considering tags with prerelease versions as valid tags.
There was a fix[^1] in `Masterminds/semver` package, which `argocd-image-updater` uses for semver checks. This fix was included in the v3.2.0 release[^2] of `Masterminds/semver` and the lastest release is `v3.2.1`.
Therefore I have upgraded the version of `Masterminds/semver` package from v1 .5.0to v3.2.1.
I have verified that the `x-0` constraint correctly handles prerelease tags by the following test code.
The test code includes multiple test cases to cover various scenarios.
<details><summary>Details</summary>
<p>
```go …
```
=> chore(deps): Upgrade the version of semver package from v1 to v3

.github/workflows/ci-tests.yaml, .golangci.yml
This PR fixes [Issue #706](https://github.com/argoproj-labs/argocd-image-updater/issues/706)
=> Fix: golangci lint

docs/install/installation.md
Replace invalid GitHub url reference with the right one that points to the codebase on the master branch.
=> doc: Update installation.md

Dockerfile
Related to: https://github.com/alpinelinux/docker-alpine/issues/396
=> fix: downgrade alpine version, while aws cli is not available in 3.20

pkg/argocd/gitcreds.go
Closes: https://github.com/argoproj-labs/argocd-image-updater/issues/621
=> fix: invalid memory address due to store is nil in gitcreds.go

hack/release.sh
This PR fixes the logic to check for the existence of a tag.
With the current logic, `tag -l "${TARGET_VERSION}"` produces no output since the TARGET_VERSION is something like `0.13.1`, while tags are in the form of `v0.13.1`, so the whole condition always evals to false, even with an existing tag.
=> chore: fix checking for the existence of TARGET_TAG

.github/workflows/init-release.yaml
Fixes #734 
This PR adds a github actions on-demand workflow that contains necessary steps to prepare a release. This workflow is modelled after the script https://github.com/argoproj-labs/argocd-image-updater/blob/master/hack/release.sh, minus the last few steps in the end.
Note that this workflow only prepares the release, and the responsible release engineer is still responsible for verifying the output, and continue with further manual steps in order to finish the releasing.
A screenshot of the workflow input fields:
https://gist.github.com/chengfang/32f8c6f31fb0736476677abe1b8cc451
After a successful test run of the workflow in my fork, the following test PR in my fork was created:
https://github.com/chengfang/argocd-image-updater/pull/7
=> create github actions workflow init-release.yaml for preparing release

.github/actions/spelling/expect.txt, cmd/main.go, cmd/run.go, docs/basics/update-methods.md, ext/git/client.go, ext/git/mocks/Client.go, ext/git/writer.go, manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/install.yaml, pkg/argocd/git.go, pkg/argocd/update.go
Building upon the work done in [PR 428](https://github.com/argoproj-labs/argocd-image-updater/pull/428) to add support for SSH signed commits. 
Updated Documentation to include instructions and examples for adding an SSH signing key along with links to repository provider documentation for setting up commit verification.  
Updated deployment to include volumes for SSH key secrets and the respective volume mounts.
=> Added support for ssh signed commits and completed gpg signed commit work

manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/install.yaml
Fix issue with volume `ssh-git-creds` (introduced in #710) that prevents to install `master` branch
`optional: true` was missing an indent
=> Fix issue regarding volume added in #710

docs/basics/update-methods.md, manifests/base/deployment/argocd-image-updater-deployment.yaml, manifests/install.yaml
Moved ssh key mount for signing key into a new `ssh-keys` directory. This is to avoid trying to mount in an existing .ssh directory.
=> fix: fixed path for ssh signing key, error mounting in another volume

pkg/argocd/gitcreds.go
Pass the git store from the write back config to the git credential functions.
Fixes:
- https://github.com/argoproj-labs/argocd-image-updater/issues/728
- https://github.com/argoproj-labs/argocd-image-updater/issues/754
=> fix: pass through git store to git creds

docs/configuration/applications.md, docs/index.md
For those using [Applications in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace), the docs should mention that Image Updater is not compatible with any `Application` resources installed in namespaces other than `argocd`.
=> Documentation: ArgoCD apps in any namespace incompatibility

pkg/registry/client.go
=> fix: add check for the optional ref.Platform field to avoid nil pointer in TagInfoFromReferences

pkg/argocd/git.go, pkg/argocd/git_test.go
This commit causes argocd-image-updater to preserve the order of fields in the `kustomization.yaml` file when updating the image(s). Doing so will minimize git diffs in the case that other tools also edit the `kustomization.yaml` file.
Fixes #502
=> Preserve field order when updating kustomization.yaml file

pkg/argocd/update.go, pkg/argocd/update_test.go
When updating multiple images in a Helm values file, ArgoCD would only ever update a single image. This is because the code only takes into account the new helm values from the last image that it processed ignoring the changes for the previous images.
This commit fixes that behavior. The `helmNewValues` var is moved outside of the for-loop that iterates over the app images. For each image, the tag is updated in the `helmNewValues` var.
Fixes #786
=> Fix updates to multiple images when using helm values file

pkg/image/image.go, pkg/image/image_test.go
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/806
=> fix: Improper parsing of image identifiers having both tag name and digest

.github/workflows/ci-tests.yaml, .golangci.yml
To fix the warning with recent golangci-lint versions: `WARN [lintersdb] The name "vet" is deprecated. The linter has been renamed to: govet.`
golangci-lint v1.59.1:
https://github.com/golangci/golangci-lint/releases/tag/v1.59.1
=> chore(deps): upgrade golangci-lint from v1.57.2 to v1.59.1; change golangci-lint vet to govet

cmd/run.go, docs/install/reference.md, pkg/argocd/argocd.go, pkg/argocd/argocd_test.go, pkg/argocd/mocks/ArgoCD.go
Filter labels on the server instead of client
* This will allow supporting filtering by more label options
* Multiple labels
* Negative matching
* Label exists regardless of value
* This should reduce cpu, memory, and networking resources needed
* Updated docs to reflect new capabilities
=> feat!: Filter labels on the server instead of client to allow more label filtering options

ext/git/client.go, ext/git/git_test.go, ext/git/mocks/Client.go, ext/git/writer.go, pkg/argocd/git.go, pkg/argocd/update_test.go
* Only git fetch the one target revision that we need
* This does not utilize the history so there is no reason to clone it
* For large repos, this will speed up performance significantly
=> feat: Use shallow clone to speed up performance

pkg/argocd/update.go, pkg/argocd/update_test.go
* This was previously supported, but broke when the function was refactored to preserve order of yaml file (#748)
* Behavior does not change if overriding an existing value
* If the values file is empty or does not have a previous value, add the value instead of erroring
=> Allow setting new value in Helm values file

pkg/argocd/argocd.go, pkg/argocd/update_test.go
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/809
For multiple aliases pointing to the same image, parameters for each alias should be updated according to the application annotations. The test is contributed by dshmelev.
=> fix: Multiple aliases for the same image only 1 parameter is updated

pkg/image/options_test.go, pkg/options/options.go, pkg/options/options_test.go, pkg/registry/client.go
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/711
* change `WantsPlatform()` method to allow match of broader platform
* add unit tests for the above change
* improve logs to include platform variant so it's clear why certain match is false
* this fix causes some change of behavior in comparing options platforms vs platforms of available images, as shown in the changes to `pkg/image/options_test.go`
=> fix: allow the specific image platform os/arch/variant to meet the requirement for a broader image platform os/arch

manifests/base/rbac/argocd-image-updater-clusterrole.yaml, manifests/base/rbac/argocd-image-updater-clusterrolebinding.yaml, manifests/base/rbac/kustomization.yaml, manifests/install.yaml, pkg/kube/kubernetes.go, pkg/kube/kubernetes_test.go
Sync namespace for Event to the Application namespace (#847)
Note that this does assume that the kubernetes client has permissions to create Events on the particular namespace (this typically depends on cluster RBAC)
=> feat: Sync namespace for Event to the Application namespace (#847)

pkg/argocd/update.go, pkg/argocd/update_test.go
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/840
=> fix: failed to process a full image-spec annotation with git writeback to helmvalues

pkg/registry/client_test.go
Closes https://github.com/argoproj-labs/argocd-image-updater/issues/839
=> tests: Improve unit tests for pkg/registry/client.go

pkg/argocd/git.go, pkg/argocd/git_test.go
Related: https://github.com/argoproj-labs/argocd-image-updater/issues/371
- If a change to manifest is not synced, image updater will keep trying to update the image and try to produce a commit without any changes, this is resulting in error log and metrics which is noisy
- This PR will skip commit for kustomization file when nothing is changed. this case can happen when the manifest in git is not synced
=> fix: Kustomize skip commit if nothing changed

pkg/argocd/git.go
Closes https://github.com/argoproj-labs/argocd-image-updater/issues/673 https://github.com/argoproj-labs/argocd-image-updater/issues/879
=> fix(git): write back to custom git branch failed by rejected push: tip of your current branch is behind

pkg/argocd/argocd.go, pkg/env/env.go, pkg/env/env_test.go
Address comments in https://github.com/argoproj-labs/argocd-image-updater/pull/854.
=> chore: Address comments in PR #854

pkg/argocd/update.go, pkg/argocd/update_test.go
Closes https://github.com/argoproj-labs/argocd-image-updater/issues/884
=> fix: Git write back to helm values is incorrect during the first pass and corrupts existing data

Makefile
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/898
=> fix: add build steps to create binary checksum and signature files

pkg/log/log.go
This is an approach to fix https://github.com/argoproj-labs/argocd-image-updater/issues/903
However, there are still some info level logs printed. 
```
time="2024-10-31T08:51:43Z" level=info msg=Trace args="[git config user.name argocd]" dir=/tmp/git-rainmaker3532605552 operation_name="exec git" time_ms=1.117718
```
These logs are generated by codes listed below
1. https://github.com/argoproj-labs/argocd-image-updater/blob/master/ext/git/client.go#L814
2.  https://github.com/argoproj/argo-cd/blob/master/util/exec/exec.go#L54
3. https://github.com/argoproj/gitops-engine/blob/master/pkg/utils/tracing/logging.go#L43
They provided a way to set the log level, which is here https://github.com/argoproj/argo-cd/blob/master/util/log/logrus.go#L55. We can use the environment variable …
=> fix: respect log level settings

pkg/argocd/git.go
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/895
This PR changes how a custom git write-back branch is created. Please review and look for any side effects. See issue comments https://github.com/argoproj-labs/argocd-image-updater/issues/895#issuecomment-2451024639
Tested with the following scenarios with the following [app config](https://github.com/chengfang/image-updater-examples/blob/main/push-branch-kustomize/app/push-branch-kustomize.yaml):
```yaml
annotations:
argocd-image-updater.argoproj.io/image-list: nginx=nginx:1.16.x
argocd-image-updater.argoproj.io/update-strategy: semver
argocd-image-updater.argoproj.io/force-update: "false"
argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
argocd-image-updater.argoproj.io/git-branch: …
```
=> fix: #895 Image Updater continuously force-pushes new commits when checkout branch is specified

pkg/argocd/argocd.go, pkg/argocd/argocd_test.go
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/896
=> fix: #896 App of apps being overwritten by image-updater

pkg/argocd/git.go, pkg/argocd/update_test.go
In https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/argocd/git.go#L161-L167, it sets git.username and git.email config to the git client. These 2 configs are used by commit operation later. In some cases, the commit operation will not be needed, either because there are errors before the commit, or because the commit should be skipped due to absence of real changes.
This PR delays setting these 2 configs, which involves calling git command twice, till before the commit operation. In addition to the savings from skipping the 2 command calls, the logs will also be cleaner.
=> fix: delay setting git.username and git.email config till commit time

Makefile, hack/gpg-key.conf
This PR fixes the github action draft release failure in signing binaries.
=> fix(build): add step to Makefile to generate signing gpg key

Makefile
This is a trivia fix to trigger github release draft action, after adding `release` label.
=> chore: fix the .phony target name for multiarch-image-push

.github/cherry-pick-bot.yml
This PR enables a [cherry-pick-bot](https://github.com/googleapis/repo-automation-bots/tree/main/packages/cherry-pick-bot) that will automate cherry picks into a PR.
=> chore: add cherry-pick-bot

.github/workflows/ci-tests.yaml
https://github.com/golangci/golangci-lint/releases/tag/v1.61.0
=> chore(deps): upgrade golangci-lint from 1.59.1 to 1.61.0

pkg/argocd/argocd.go, pkg/argocd/update.go
When the write-back method is ArgoCD, the Image Updater sends an update to the ArgoCD Application on each iteration. No matter whether the new image has already been set or not, it always sends the update. In a situation where autoSync is disabled, this means that it continuously sends updates until somebody syncs the Application.
To reduce updates and improve resource usage, this pull request slightly changes the behavior. The Image Updater will check if the new image is already set in the Application source to apply the update or ignore it.
We have tested the changes in our ArgoCD instance to check the feature and you can see the results in the image below. Updates have been reduced. Once they are applied, updates disappear. CPU and memory usage have been improved.
=> Improve Application updates when write-back method is ArgoCD

go.mod, registry-scanner/go.mod
https://pkg.go.dev/k8s.io/client-go#section-readme
<details><summary>Details</summary>
<p>
</p>
</details> 
migrates to newer scheme to match kubernetes releases.
=> update k8s.io/client-go from v1.5.2 to v0.31.0

go.mod
```bash
🔎 Scanning "packages/x86_64/argocd-image-updater-0.15.1-r0.apk"
└── 📄 /usr/bin/argocd-image-updater
📦 github.com/docker/distribution v2.8.1+incompatible (go-module)
High CVE-2023-2253 GHSA-hqxw-f8mx-cpmw fixed in 2.8.2-beta.1
```
context: I'm packaging it [here](https://github.com/wolfi-dev/os/pull/37040) and this is being flagged out as a CVE by the scanner.
=> remove docker/distribution replace from go.mod

.github/workflows/ci-tests.yaml
see https://github.com/codecov/codecov-action/tree/main?tab=readme-ov-file#arguments for codecov-action parameters.
=> chore(ci): use files parameter in codecov-action instead of file, which was deprecated and removed

Dockerfile
cherry-pick from master to release-0.15 branch to fix the issue of missing gpg-agent package
=> fix: Add gpg-agent to container image (#978)

pkg/argocd/update.go
cherry-pick from master to release-0.15 to fix the issue of changed default file name for git write-back target
=> fix: Image updater changes git write back file (#970)

docs/basics/update-strategies.md, docs/install/installation.md
I'm not entirely sure of the correct syntax or the process for testing these docs locally (just doing a drive-by commit on GitHub). I noticed that some of the Warning blocks in the docs had broken formatting. This PR should fix that.
=> docs: correct formatting issues

pkg/argocd/git.go, pkg/argocd/git_test.go
Hi,
I've created a PR that should solve #501. First time I (really) contribute to an open-source project, so feel free to criticize anything I may have done wrong!
I have based this PR on the v0.15.2 branch instead of master as master was failing for me (throwing panics at runtime in my cluster). Let me know whether this is fine.
I've basically changed the way the `updateKustomizeFile` function in `pkg/argocd/git.go` works. It now uses `kio.ByteReadWriter`, which allows to preserve sequence indentation. 
I also had to slightly modify how the comparison is done: `kio` adds some `metadata.annotations` to the yaml document, hence my approach was to get the output from the writer (which clears those annotations), and then parse it again with `kyaml`, hence ensuring that indentation is the …
=> Keep yaml sequence indentation when writing back to Git to a kustomize file

go.mod, go.sum, pkg/argocd/argocd.go, pkg/argocd/argocd_test.go, pkg/argocd/update.go, pkg/argocd/update_test.go, pkg/common/constants.go
The common helper was created in https://github.com/argoproj-labs/argocd-image-updater/pull/1010. This PR replaces the common constants with the prefix specific to argocd-image-updater.
=> Replace common constant references

pkg/argocd/git.go
I'm not entirely sure when this happens, but the kustomize can be nil. Accessing Images then leads to a nil-deref.
With this approach, the updater defaults to empty images when it cannot get the real ones.
=> fix: Prevent segfault with empty kustomization

pkg/argocd/update.go, pkg/argocd/update_test.go
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/1034
Modified `mergeKustomizeOverride` method to have more control over setting and adding parameters to `.argocd-source-*.yaml` target file.
=> fix(write-back): Duplicate image entries with different formats when updating two images

go.mod, pkg/argocd/update.go, pkg/argocd/update_test.go
Similar to #1039 (and conflicts with it). In our codefresh install developers have complained that various parts of the original yaml aren't preserved:
- comments
- multiline string formatting for parameters like scripts
- anchors (the current code resolves all anchors and writes back with no anchors, resulting in duplicative config)
In particular we have cases where multiple jobs are defined in a chart which use the same images, which should all be updated via a single reference. yaml.v2 doesn't support this, but yaml.v3 does; the Node structure preserves pre-, post- and end-of-line comments, keeps the string formatting marker with the string for marshalling, and allows us to navigate aliases without losing them.
In this PR, I first switched to yaml.v3, then, like #1039, simplified the …
=> Move to yaml.v3 and preserve comments, multiline strings, anchors in helm values

test/e2e/Makefile, test/e2e/README.md, test/e2e/bin/install.sh, test/e2e/containers/git/entrypoint.sh
1. Update `/etc/rancher/k3s/registry.yaml` to `registries.yaml` according to https://docs.k3s.io/installation/private-registry
2. Use `nginx:git` permissions for git project root for private git server. It fixes 500 connection error.
3. Add `delete-prereqs` Makefile rule.
4. Update README.md
=> Set up custom container registry and git server for image-updater e2e tests.

go.mod, pkg/argocd/update.go, pkg/argocd/update_test.go
We had some grumbles from developers after the goyaml.v3 upgrade that this changed the compact sequence indent used by kustomize, kubectl etc.
There was a whole thread about this when the goyaml.v3 upgrade happened in kustomize itself: https://github.com/kubernetes-sigs/kustomize/issues/3946 and the result was that kubesigs forked goyaml.
In order to more closely match what the kubernetes tools do, this commit switches to the forked version, which has a compact option on the encoder:
https://github.com/kubernetes-sigs/yaml/blob/56d672052dcff7362af5b66f6424976539cddd78/goyaml.v3/patch.go#L25-L28
When I first tried this I also changed the code to guess if compact was the preferred style from the yaml. However, it turns out that the yaml formatter misbehaves when told to use "compact" and an …
=> fix: use compact indent for sequences

.github/workflows/ci-tests.yaml
to fix various golangci-lint failures in recent PRs.
=> chore(deps): bump golangci-lint from v1.61.0 to v1.64.8

registry-scanner/pkg/env/env.go, registry-scanner/pkg/env/env_test.go
Adds a new utility function `GetDurationVal` to retrieve a time.Duration from an environment variable, with a default value fallback and error logging.
=> feat: Add GetDurationVal to handle optional duration config from env

go.mod, go.sum
upgrade argo-cd to the latest z-stream release
=> chore(deps): bump argo-cd from 2.13.6 to 2.13.7

docs/configuration/images.md
This PR will update image update strategy docs in the Configuration section.
The strategy names were upadted in the Basics section but the Configuration was missed
=> chore(docs): Update update strategy docs on deprecated strategy values

.github/workflows/ci-tests.yaml, .github/workflows/create-release-draft.yaml
Fixes #1131 
the go versions in the GitHub action workflows are hardcoded. Updated files that include the issue to fix that.
=> chore(ci): update ci-tests.yaml and create-release-draft.yaml to use go version from go.mod

registry-scanner/pkg/log/log.go
Thanks to them, we can pass a contextual logger down through a call stack: `controller=ctrl controllerGroup=ctrlG controllerKind=ctrlK logger=lgr`.
Will be used in future CRD feature. See #1170
=> Add helpers to return a new `context.Context` that carries the provided logrus Entry.

api/v1alpha1/imageupdater_types.go, config/crd/bases/argocd-image-updater.argoproj.io_imageupdaters.yaml, config/samples/argocd-image-updater_v1alpha1_imageupdater.yaml, pkg/argocd/argocd.go, pkg/argocd/argocd_test.go, registry-scanner/pkg/image/options.go
As requested in #1193 we are moving `platforms` slice in `commonUpdateSettings`.
=> fix: CRD: Move `platforms` in the `commonUpdateSettings`.

cmd/main.go, cmd/run.go, cmd/webhook.go, pkg/webhook/docker.go, pkg/webhook/docker_test.go, pkg/webhook/quay.go, pkg/webhook/quay_test.go, pkg/webhook/server.go
This PR aims to add a Quay webhook processor to the webhook feature for Image Updater. This is accomplished by using the handler model that is used in the implementation. The handler is added along with the unit tests for it. 
On top of adding the webhook handler for quay, there is also some other enhancements to the feature in this PR. The list is below.
Enhancements:
- Fixed issues with the Git Write Back method by passing Git credentials to the webhook server which was not done in the initial implementation. 
- Made the webhook command more in line with the run command by adding similar options that were not present before. 
- Fixed some issues regarding secrets and added a secrets mechanism for Docker and Quay (More on this below) 
Secrets Changes:
The original implementation has this …
=> feat(webhook): add webhook handler for quay.io and make improvements to the community PR

api/v1alpha1/imageupdater_types.go, cmd/template.go, pkg/argocd/argocd.go, pkg/argocd/argocd_test.go, pkg/argocd/git.go, pkg/argocd/git_test.go, pkg/argocd/gitcreds.go, pkg/argocd/gitcreds_test.go, pkg/argocd/types.go, pkg/argocd/update.go, pkg/argocd/update_test.go, registry-scanner/pkg/image/image.go
1. Use pointers instead of values in `HelmTarget` and `KustomizeTarget` type.
To support cascading configuration model (global -> application -> image-specific), fields within  `HelmTarget` and `KustomizeTarget` have been changed from value types (e.g., string) to pointer types (*string). 
This  allows the system to distinguish between a "zero value" (like an empty string or false) and nil. 
I remember about https://github.com/argoproj-labs/argocd-image-updater/pull/1134#discussion_r2096466253 but I think ArgoCD had a reason to use values. In our case pointers are much more convenient. 
2. `ManifestTarget` settings were added to the `Image` struct.
3.  `GetHelmImage`, `SetHelmImage`, `GetKustomizeImage`, `SetKustomizeImage` now use CRD fields instead of annotations.
4. New function …
=> feat(crd): introduce `ManifestTarget`

cmd/webhook.go, docs/configuration/webhook.md, docs/install/cmd/run.md, docs/install/cmd/webhook.md, mkdocs.yml
Adds documentation for the webhook feature. 
Changes:
- Updates the `run` page with new webhook related flags
- Adds the documentation for `webhook` command
- Adds a configuration page with information about configuring the webhook 
- Removed some flags that I realized were not used from the `run` command
=> docs(webhook): add documentation for webhook feature

docs/configuration/images.md, pkg/argocd/update.go, pkg/argocd/update_test.go
Closes #1206
Closes #1032
Fixes a situation where it was impossible to update images that were in the yaml array.
The code can probably be improved, I will be glad to follow the recommendations.
=> feat: Allow yaml.SequenceNode type

Dockerfile, go.mod, go.sum
Current go.mod references a fixed version of registry-scanner library. Often we need to modify registry-scanner library API and use that in image-updater in the same commit or pull request. In local environment, we can manually uncomment the replace line, but CI checks will fail. The usual fix to this problem is to split the changes into 2 pull requests: the 1st for the changes in registry-scanner, and 2nd for the changes in image-updater referencing the newly updated registry-scanner API. Some pull requests (e.g., #1231) were experiencing this issue.
This PR enables immediate use of any changes in registry-scanner across image-updater codebase.
=> chore(deps): bump registry-scanner version to the latest in master, and activate the its replace clause for development

.github/workflows/ci-tests.yaml, Makefile
Cherry-picks b179e94 from master to crd branch, and also updates golangci-lint in Makefile.
=> chore(golangci-lint): add golangci-lint step for registry-scanner submodule; bump golangci-lint from 2.1.6 to 2.5.0
