argoproj-labs/argocd-image-updater

- cmd/main.go
- pkg/argocd/argocd.go
Litte refactoring for reducing amount of client requests sent to ArgoCD API
> refactor: Reduce ArgoCD client requests

- cmd/main.go
- go.mod
> feat: Allow application updates to run simultaneously

- CHANGELOG.md
- cmd/main.go
- pkg/argocd/argocd.go
- pkg/image/image.go
- pkg/image/image_test.go
- pkg/image/version.go
- pkg/image/version_test.go
- pkg/tag/tag.go
- pkg/tag/tag_test.go
This will allow us to store i.e. upload timestamps
> enhancement: Allow storing metadata along with image tag information

- .github/actions/spelling/expect.txt
- pkg/argocd/update.go
- pkg/argocd/update_test.go
- pkg/image/options.go
- pkg/image/options_test.go
- pkg/registry/client.go
- pkg/registry/registry.go
> feat: Enable unique pull secrets per image

- .github/workflows/ci-tests.yaml
- hack/generate-manifests.sh
- manifests/base/deployment/argocd-image-updater-deployment.yaml
- manifests/base/kustomization.yaml
> fix: Use Kustomize v2 for manifest generation to support kubectl apply -k

- pkg/image/version.go
As discussed in Slack, image-updater checks that tags conform to SemVer even when using a regex pre-filter. This skips that check unless the sort mode is set to `VersionSortSemVer`.
Not sure if this is the best solution, but I am now able to deploy the most recent image (by timestamp) that matches my regexp.
Signed-off-by: Michael Goodness <michael.goodness@mlb.com>
> Only check semver & constraint if sorting by semver

- pkg/argocd/update.go
- pkg/argocd/update_test.go
> fix: Allow multiple same images to be updated differently

- docs/contributing/development.md
Adding a tip to windows users.
First PR into any argo project. Be gentle.
> Documentation for Windows developers

- pkg/image/image.go
> fix: Correctly handle version constraints with equal sign

- pkg/argocd/argocd.go
- pkg/argocd/argocd_test.go
- pkg/argocd/update.go
> fix: Application spec updates should be atomic

- docs/configuration/images.md
- docs/configuration/registries.md
- pkg/registry/config.go
- pkg/registry/endpoints.go
- pkg/registry/endpoints_test.go
> feat: Allow insecure TLS connections to registries

- .github/actions/spelling/allow.txt
- pkg/image/credentials.go
- pkg/image/credentials_test.go
- test/testdata/docker/valid-config-noproto.json
> fix: Correctly parse & use pull secret entries without protocol

- cmd/main.go
- docs/install/running.md
- docs/install/start.md
- manifests/base/deployment/argocd-image-updater-deployment.yaml
- manifests/install.yaml
Also, updates getting started docs.
Closes #98
> feat: Allow setting log level from configmap (and environment)

- docs/configuration/images.md
- pkg/argocd/update.go
- pkg/common/constants.go
- pkg/image/options.go
- pkg/image/options_test.go
- pkg/image/version.go
- pkg/registry/registry.go
> feat: Allow ignoring set of tags

- .github/actions/spelling/allow.txt
- config/example-config.yaml
- docs/configuration/registries.md
- pkg/registry/config.go
- pkg/registry/config_test.go
- pkg/registry/endpoints.go
- pkg/registry/endpoints_test.go
- pkg/registry/registry.go
- pkg/registry/registry_test.go
This PR adds support for expiring credentials on registry level
> feat: Support for expiring credentials

- Dockerfile
> chore: Update to Golang v1.14.13

- pkg/image/credentials.go
> fix: Prevent nil pointer dereference in image creds

- docs/configuration/images.md
> docs: Warning about latest update strategy with Docker Hub

- .github/actions/spelling/excludes.txt
- hack/release.sh
- hack/upload-release-assets.sh
> chore: add some release creation scripts

- cmd/main.go
- pkg/argocd/update.go
- pkg/argocd/update_test.go
- pkg/image/credentials.go
- pkg/image/credentials_test.go
- pkg/kube/kubernetes.go
- pkg/kube/kubernetes_test.go
- pkg/registry/registry.go
> refactor: Rename package client to kube

- Dockerfile
> fix: install missing git binary

- .github/actions/spelling/excludes.txt
> chore: Don't run spell checker on Dockerfile

- .github/actions/spelling/allow.txt
- cmd/main.go
- docs/configuration/applications.md
- ext/git/client.go
- ext/git/mocks/Client.go
- manifests/base/deployment/argocd-image-updater-deployment.yaml
- manifests/install.yaml
- pkg/argocd/update.go
- pkg/argocd/update_test.go
This also includes a small refactoring of how to parametrize the main update loop.
> feat: Allow setting Git user and e-mail for commits

- pkg/image/credentials.go
- pkg/image/credentials_test.go
This PR fix https://github.com/argoproj-labs/argocd-image-updater/issues/195
> fix: Add suffix check for docker registry (#195)

- docs/configuration/applications.md
fix document of https://argocd-image-updater.readthedocs.io/en/stable/configuration/applications
> fix document

- .github/workflows/ci-tests.yaml
- Dockerfile
- go.mod
- go.sum
> chore: Upgrade Go to v1.16.5

- docs/requirements.txt
RTD builds are broken since quite a couple of weeks.
> chore: Fix readthedocs builds

- .github/actions/spelling/allow.txt
- docs/index.md
> docs: Mention support channels and some fixes

- .github/actions/spelling/allow.txt
- docs/install/start.md
> docs: Use versioned installation manifests in install docs

- .github/actions/spelling/allow.txt
- Makefile
> chore: New extract-binary target for easy extraction of binary

- Dockerfile
> feat: Provide aws-cli in container image

- pkg/argocd/argocd.go
- pkg/argocd/update_test.go
> fix: multiple image with alias

- .github/workflows/image.yaml
> fix: Fix docker environment variable

- .github/workflows/codeql-analysis.yml
> chore: Create codeql-analysis.yml

- Dockerfile
> chore: Upgrade golang to 1.16.13

- cmd/test.go
- pkg/argocd/argocd.go
- pkg/argocd/git.go
- pkg/argocd/update.go
- pkg/image/image.go
- pkg/image/options.go
- pkg/image/version.go
- pkg/log/log.go
- pkg/options/options.go
- pkg/registry/client.go
- pkg/registry/registry.go
- pkg/registry/registry_test.go
This PR refactors some of the logging to provide more additional context information.
> refactor: Refactor logging to provide more context information

- test/e2e/containers/git/testdata/004-multi-images/deployment.yaml
- test/e2e/containers/git/testdata/004-multi-images/kustomization.yaml
- test/e2e/suite/004-multiple-images/01-assert.yaml
- test/e2e/suite/004-multiple-images/01-install.yaml
- test/e2e/suite/004-multiple-images/02-assert.yaml
- test/e2e/suite/004-multiple-images/02-run-updater.yaml
- test/e2e/suite/004-multiple-images/99-delete.yaml
- test/e2e/testdata/004-multi-images/deployment.yaml
- test/e2e/testdata/004-multi-images/kustomization.yaml
> test: Add e2e test for multiple images

- .github/actions/spelling/expect.txt
> docs: Expect some more things in spelling

- cmd/test.go
Support for specifying multiple target platforms in `--platforms` parameter to `test` command.
> feat: Support multiple platforms for test command

- cmd/test.go
> chore: Log warning in test command on unsupported container platform

- .github/workflows/ci-tests.yaml
- Dockerfile
- go.mod
- go.sum
> chore: Bump Go and Argo CD versions

- Makefile
- hack/release.sh
> chore: Make release script multi-arch aware

- hack/release.sh
> chore: Fix release script

- hack/upload-multiarch-release-assets.sh
> chore: Correctly upload release assets

- .github/actions/spelling/expect.txt
- SECURITY.md
> docs: Add security policy

- Makefile
- docs/contributing/development.md
Signed-off-by: Kostis Kapelonis <kostis@codefresh.io>
Added the same mechanism to preview documentation like the other Argo Projects
> build: preview docs locally

- Dockerfile
Fixes: #496 
Signed-off-by: Pavel Aborilov <aborilov@gmail.com>
> fix: add ca-certificates to the docker image

- .github/actions/spelling/allow.txt
> chore: Add words to dictionary

- docs/requirements.txt
> chore: Fix building readthedocs

- docs/basics/update.md
Hi, 
Just a redirection fix in docs
> Docs: fix redirection path

- ext/git/writer.go
This fixes issue #727 git: 'git' is not a git command
> Remove repeated git command

- Dockerfile
- ext/git/writer.go
Fixes #754
Actually, gpg binary was missing from Dockerfile too.
> fix: Fix write-back commits

- pkg/argocd/gitcreds_test.go
- pkg/argocd/update_test.go
Increase code coverage for `pkg/argocd` package
> tests: Add unit tests for pkg/argocd

- test/e2e/prereqs/argocd/kustomization.yaml
Closes https://github.com/argoproj-labs/argocd-image-updater/issues/845
> chore: update argocd version in test/e2e/prereqs/argocd/kustomization.yaml

- .github/workflows/create-release-draft.yaml
> fix: pass image tag into build image command

- registry-scanner/go.mod
- registry-scanner/go.sum
- registry-scanner/pkg/health/health.go
- registry-scanner/pkg/health/health_test.go
- registry-scanner/pkg/log/log.go
- registry-scanner/pkg/log/log_test.go
- registry-scanner/pkg/options/options.go
- registry-scanner/pkg/options/options_test.go
- registry-scanner/pkg/tag/semver.go
- registry-scanner/pkg/tag/tag.go
- registry-scanner/pkg/tag/tag_test.go
- registry-scanner/test/fixture/capture.go
Add additional packages to registry-scanner.
* pkg/log
* pkg/health
* pkg/options
* pkg/tag
> refactor: Add additional packages to registry-scanner

- CODEOWNERS
- OWNERS
Add @ishitasequeira to maintainers.
> docs: Update OWNERS

- pkg/argocd/update.go
Fixes https://github.com/argoproj-labs/argocd-image-updater/issues/963
> fix: Image updater changes git write back file

- .github/workflows/ci-tests.yaml
Update CI to run tests for registry-scanner separately
> Update CI to run tests for registry-scanner separately

- Dockerfile
> fix: Add gpg-agent to container image

- .readthedocs.yml
- cmd/util.go
- pkg/kube/kubernetes.go
- pkg/kube/kubernetes_test.go
Initialize the kubeClient and applicationsClientSet correctly
Fixes #1021
> Initialize the kubeClient and applicationsClientSet correctly

- go.mod
- go.sum
https://github.com/argoproj/argo-cd/releases/tag/v2.13.5
> chore(deps): upgrade argo-cd from 2.13.4 to 2.13.5

- registry-scanner/pkg/image/kustomize.go
- registry-scanner/pkg/image/kustomize_test.go
Sync up registry-scanner/pkg/image/kustomize.go with argo-cd
> fix: fix KustomizeImage Match function to pass added unit tests

- .github/workflows/ci-tests.yaml
- .github/workflows/create-release-draft.yaml
in go.mod, go version is already 1.23.
> chore(deps): bump go version from 1.22 to 1.23 in github action files

- go.mod
- go.sum
This change Upgrade argo-cd version from 2.13.5 to 2.13.6
> chore(deps): Upgrade argo-cd version to 2.13.6

- registry-scanner/pkg/log/log.go
> fix: respect log level settings

- api/v1alpha1/imageupdater_types.go
- config/manager/kustomization.yaml
- internal/controller/imageupdater_controller.go
- internal/controller/imageupdater_controller_test.go
- Draft for Reconcile function and test for it
> Initial version of the controller

- pkg/argocd/update.go
Removed dummy digest for workaround add comparison logic
> fix: remove dummy digest and add comparison logic

- README.md
- cmd/webhook.go
- cmd/webhook_test.go
- docs/basics/authentication.md
- docs/basics/update-methods.md
- docs/basics/update-strategies.md
- docs/basics/update.md
- docs/configuration/applications.md
- docs/configuration/images.md
- docs/configuration/migration.md
- docs/configuration/registries.md
- docs/examples/index.md
- docs/index.md
- docs/install/cmd/run.md
- docs/install/cmd/test.md
- docs/install/cmd/webhook.md
- docs/install/testing.md
- mkdocs.yml
- pkg/webhook/docker_test.go
- pkg/webhook/ghcr_test.go
- pkg/webhook/harbor_test.go
- pkg/webhook/webhook_test.go
- Refactor legacy annotation based documentation
- Add migration guide
- Rename vars in webhook.go
> docs(crd): update community documentation

- Dockerfile
In manager.yaml
```
containers:
- command:
- /manager
args:
- run
image: controller:latest
```
> chore(crd): align path in Dockerfile with command in manager.yaml
